# キックの種類を定義
uint8 KICK_TYPE_UNKNOWN = 0
uint8 KICK_TYPE_STRAIGHT = 1
uint8 KICK_TYPE_CHIP = 2
uint8 KICK_TYPE_DISCHARGE = 3

# キックの種類
uint8 kick_type

# キックパワー [m/s]
float32 kick_power
---
# キックに成功したらtrueを返す
bool success
# キック結果の詳細。エラー情報を返してもよし
string message
