name: foxy-build

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - { ROS_DISTRO: foxy, ROS_REPO: ros }

    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      - name: Install pigpio
        run: |
          cd $HOME
          git clone https://github.com/joan2937/pigpio
          cd pigpio
          make
          sudo make install
      - uses: actions/checkout@v2
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}