name: Build and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: foxy}
          - { ROS_DISTRO: humble }
          - { ROS_DISTRO: jazzy }

    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.env.ROS_DISTRO }}-ros-base
    steps:
      - name: Install pigpio
        run: |
          cd $HOME
          git clone https://github.com/joan2937/pigpio
          cd pigpio
          make
          sudo make install
      - name: Build Workspace
        run: |
          . /opt/ros/${{ matrix.env.ROS_DISTRO }}/setup.sh
          mkdir -p ros2_ws/src
          cd ros2_ws
          colcon build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/frootspi
      - name: Build 
        run: |
          . /opt/ros/${{ matrix.env.ROS_DISTRO }}/setup.sh
          cd ros2_ws/src
          git clone https://github.com/SSL-Roots/consai_frootspi_msgs.git
          git clone https://github.com/SSL-Roots/frootspi_msgs.git
          apt update
          rosdep update
          rosdep install -r -y -i --from-paths .
          cd ..
          colcon build --symlink-install
      - name: Test
        run: |
          . /opt/ros/${{ matrix.env.ROS_DISTRO }}/setup.sh
          . ros2_ws/install/setup.sh
          cd ros2_ws
          colcon test
          colcon test-result --verbose